apiVersion: v2
name: code-interpreter
description: A Helm chart for Code Interpreter - FastAPI service to execute Python code in isolated environments
type: application
version: 0.2.1
appVersion: latest
keywords:
  - code-execution
  - python
  - fastapi
  - sandbox
home: https://github.com/onyx-dot-app/python-sandbox
sources:
  - https://github.com/onyx-dot-app/python-sandbox
maintainers:
  - name: Onyx
    email: hello@onyx.app
